import { useEffect, useMemo, useRef } from "react";
import type { DesktopWidget } from "../../types/widget";
import { useWidgetStore } from "../../store/widgetStore";

type Permission = "network" | "clipboard" | "notifications" | "openExternal";
const allowedPermissions: Permission[] = ["network", "clipboard", "notifications", "openExternal"];

export function CustomWidget({widget}:{widget:DesktopWidget}) {
  const frame=useRef<HTMLIFrameElement>(null); const updateWidget=useWidgetStore(s=>s.updateWidget);
  const source=widget.data?.source as {html?:string;css?:string;js?:string}|undefined;
  const permissions=(widget.data?.permissions as Record<string,boolean>|undefined)??{};
  const srcDoc=useMemo(()=>`<!doctype html><html><head><meta charset="utf-8"><style>html,body{margin:0;min-height:100%;font-family:Segoe UI,sans-serif;color:inherit;background:transparent}${source?.css??""}</style></head><body>${source?.html??"<div>Custom widget</div>"}<script>const WidgetStudio={request:(permission,payload)=>new Promise((resolve,reject)=>{const id=crypto.randomUUID();const handler=e=>{if(e.data?.type==='widget-studio-result'&&e.data.id===id){removeEventListener('message',handler);e.data.ok?resolve(e.data.value):reject(new Error(e.data.error))}};addEventListener('message',handler);parent.postMessage({type:'widget-studio-request',id,permission,payload},'*')})};try{${source?.js??""}}catch(error){document.body.innerHTML='<pre style="color:#dc2626;white-space:pre-wrap">'+String(error)+'</pre>'}</script></body></html>`,[source]);
  useEffect(()=>{const receive=async(event:MessageEvent)=>{if(event.source!==frame.current?.contentWindow||event.data?.type!=="widget-studio-request")return;const {id,permission,payload}=event.data as {id:string;permission:string;payload:unknown};if(!allowedPermissions.includes(permission as Permission)){reply(id,false,undefined,"Unknown permission");return}let granted=permissions[permission];if(granted===undefined){granted=window.confirm(`“${widget.name}” requests ${permission} permission. Allow this widget to use it?`);updateWidget(widget.id,{data:{...widget.data,permissions:{...permissions,[permission]:granted}}})}if(!granted){reply(id,false,undefined,"Permission denied");return}try{if(permission==="clipboard"){await navigator.clipboard.writeText(String((payload as {text?:string})?.text??""));reply(id,true,true)}else if(permission==="notifications"){if(Notification.permission==="default")await Notification.requestPermission();if(Notification.permission!=="granted")throw new Error("Notification permission denied");new Notification(String((payload as {title?:string})?.title??widget.name),{body:String((payload as {body?:string})?.body??"")});reply(id,true,true)}else if(permission==="openExternal"){const url=String((payload as {url?:string})?.url??"");if(!/^https?:\/\//i.test(url))throw new Error("Only HTTP(S) URLs are allowed");window.open(url,"_blank","noopener,noreferrer");reply(id,true,true)}else if(permission==="network"){const request=payload as {url?:string;options?:RequestInit};const url=String(request?.url??"");if(!/^https:\/\//i.test(url))throw new Error("Only HTTPS requests are allowed");const response=await fetch(url,{...request.options,credentials:"omit"});reply(id,true,{status:response.status,text:await response.text()})}}catch(error){reply(id,false,undefined,error instanceof Error?error.message:"Request failed")}};const reply=(id:string,ok:boolean,value?:unknown,error?:string)=>frame.current?.contentWindow?.postMessage({type:"widget-studio-result",id,ok,value,error},"*");window.addEventListener("message",receive);return()=>window.removeEventListener("message",receive)},[permissions,updateWidget,widget.data,widget.id,widget.name]);
  return <iframe ref={frame} title={widget.name} sandbox="allow-scripts" srcDoc={srcDoc} className="h-full w-full border-0 bg-transparent" />
}
