import type { DesktopWidget } from "./widget";

export type CustomWidgetMode = "visual" | "code";
export type CustomWidgetPermission = "network" | "clipboard" | "notifications" | "openExternal";
export type VisualBlockType = "container" | "row" | "heading" | "text" | "button" | "link" | "image" | "spacer";

export interface VisualStyle { color?: string; backgroundColor?: string; fontSize?: number; fontWeight?: "400" | "500" | "600" | "700"; borderRadius?: number; padding?: number; textAlign?: "left" | "center" | "right"; }
export interface VisualBlockBase { id: string; type: VisualBlockType; }
export interface VisualContainerBlock extends VisualBlockBase { type: "container" | "row"; children: VisualBlock[]; gap: number; padding: number; style: VisualStyle; }
export interface VisualHeadingBlock extends VisualBlockBase { type: "heading"; text: string; level: 1 | 2 | 3; style: VisualStyle; }
export interface VisualTextBlock extends VisualBlockBase { type: "text"; text: string; style: VisualStyle; }
export type VisualAction = "none" | "openExternal" | "notifications" | "clipboard";
export interface VisualButtonBlock extends VisualBlockBase { type: "button"; label: string; action: VisualAction; value: string; style: VisualStyle; }
export interface VisualLinkBlock extends VisualBlockBase { type: "link"; label: string; url: string; style: VisualStyle; }
export interface VisualImageBlock extends VisualBlockBase { type: "image"; src: string; alt: string; width: number; height: number; style: VisualStyle; }
export interface VisualSpacerBlock extends VisualBlockBase { type: "spacer"; size: number; }
export type VisualBlock = VisualContainerBlock | VisualHeadingBlock | VisualTextBlock | VisualButtonBlock | VisualLinkBlock | VisualImageBlock | VisualSpacerBlock;
export interface VisualWidgetDocument { version: 1; root: VisualContainerBlock; }
export interface CustomWidgetSource { html: string; css: string; js: string; }
export type CustomWidgetPermissions = Partial<Record<CustomWidgetPermission, boolean>>;
export interface CustomWidgetData extends Record<string, unknown> { version: 1; mode: CustomWidgetMode; visual: VisualWidgetDocument; source: CustomWidgetSource; permissions: CustomWidgetPermissions; }
export interface CustomWidgetDraft { id?: string; name: string; mode: CustomWidgetMode; visual: VisualWidgetDocument; source: CustomWidgetSource; permissions: CustomWidgetPermissions; }
export const CUSTOM_WIDGET_PERMISSIONS: CustomWidgetPermission[] = ["network", "clipboard", "notifications", "openExternal"];
export function createId(prefix = "block"): string { return `${prefix}-${crypto.randomUUID()}`; }
export function createDefaultVisualDocument(): VisualWidgetDocument { return { version: 1, root: { id: "root", type: "container", gap: 10, padding: 16, style: { backgroundColor: "#ffffff", borderRadius: 16, color: "#172033" }, children: [ { id: createId("heading"), type: "heading", text: "My widget", level: 2, style: { fontSize: 24, fontWeight: "700" } }, { id: createId("text"), type: "text", text: "Build something useful with Widget Studio.", style: { fontSize: 14, color: "#526078" } }, { id: createId("button"), type: "button", label: "Say hello", action: "notifications", value: "Hello from my widget", style: { backgroundColor: "#665ee8", color: "#ffffff", borderRadius: 9, padding: 10, fontWeight: "600" } } ] } }; }
export function createVisualBlock(type: VisualBlockType): VisualBlock { if (type === "container" || type === "row") return { id: createId(type), type, gap: 8, padding: 10, style: {}, children: [] }; if (type === "heading") return { id: createId(type), type, text: "New heading", level: 2, style: { fontSize: 22, fontWeight: "700" } }; if (type === "text") return { id: createId(type), type, text: "New text block", style: { fontSize: 14, color: "#526078" } }; if (type === "button") return { id: createId(type), type, label: "Button", action: "none", value: "", style: { backgroundColor: "#665ee8", color: "#ffffff", borderRadius: 9, padding: 10, fontWeight: "600" } }; if (type === "link") return { id: createId(type), type, label: "Open link", url: "https://example.com", style: { color: "#665ee8", fontWeight: "600" } }; if (type === "image") return { id: createId(type), type, src: "https://images.unsplash.com/photo-1497250681960-ef046c08a56e?w=640", alt: "Widget image", width: 260, height: 140, style: { borderRadius: 12 } }; return { id: createId(type), type, size: 18 }; }
export function findVisualBlock(document: VisualWidgetDocument, id: string): VisualBlock | null { if (document.root.id === id) return document.root; const walk = (blocks: VisualBlock[]): VisualBlock | null => { for (const block of blocks) { if (block.id === id) return block; if ((block.type === "container" || block.type === "row") && block.children.length) { const found = walk(block.children); if (found) return found; } } return null; }; return walk(document.root.children); }
export function updateVisualBlock(document: VisualWidgetDocument, id: string, patch: Partial<VisualBlock>): VisualWidgetDocument { const update = (blocks: VisualBlock[]): VisualBlock[] => blocks.map((block) => { const next = block.id === id ? ({ ...block, ...patch } as VisualBlock) : block; if ((next.type === "container" || next.type === "row") && next.children.length) return { ...next, children: update(next.children) }; return next; }); return document.root.id === id ? { ...document, root: { ...document.root, ...patch } as VisualContainerBlock } : { ...document, root: { ...document.root, children: update(document.root.children) } }; }
export function insertVisualBlock(document: VisualWidgetDocument, parentId: string, block: VisualBlock): VisualWidgetDocument { const insert = (container: VisualContainerBlock): VisualContainerBlock => { if (container.id === parentId) return { ...container, children: [...container.children, block] }; return { ...container, children: container.children.map((child) => child.type === "container" || child.type === "row" ? insert(child) : child) }; }; return { ...document, root: insert(document.root) }; }
export function removeVisualBlock(document: VisualWidgetDocument, id: string): VisualWidgetDocument { const remove = (blocks: VisualBlock[]): VisualBlock[] => blocks.filter((block) => block.id !== id).map((block) => block.type === "container" || block.type === "row" ? { ...block, children: remove(block.children) } : block); return { ...document, root: { ...document.root, children: remove(document.root.children) } }; }
export function moveVisualBlock(document: VisualWidgetDocument, id: string, direction: -1 | 1): VisualWidgetDocument { const move = (container: VisualContainerBlock): VisualContainerBlock => { const index = container.children.findIndex((child) => child.id === id); if (index >= 0) { const target = index + direction; if (target < 0 || target >= container.children.length) return container; const children = [...container.children]; [children[index], children[target]] = [children[target], children[index]]; return { ...container, children }; } return { ...container, children: container.children.map((child) => child.type === "container" || child.type === "row" ? move(child) : child) }; }; return { ...document, root: move(document.root) }; }
export function customWidgetDataFromDraft(draft: CustomWidgetDraft, source = draft.source): CustomWidgetData { return { version: 1, mode: draft.mode, visual: draft.visual, source, permissions: draft.permissions }; }
export function draftFromWidget(widget: DesktopWidget): CustomWidgetDraft { const data = widget.data as Partial<CustomWidgetData> & { source?: Partial<CustomWidgetSource>; permissions?: CustomWidgetPermissions } | undefined; const source = { html: data?.source?.html ?? "<main><h2>Custom widget</h2></main>", css: data?.source?.css ?? "", js: data?.source?.js ?? "" }; return { id: widget.id, name: widget.name, mode: data?.mode === "visual" || data?.mode === "code" ? data.mode : "code", visual: data?.visual?.root ? data.visual as VisualWidgetDocument : createDefaultVisualDocument(), source, permissions: data?.permissions ?? {} }; }
export function normalizeCustomWidgetData(data: Record<string, unknown> | undefined): CustomWidgetData { const value = data as Partial<CustomWidgetData> & { source?: Partial<CustomWidgetSource>; permissions?: CustomWidgetPermissions } | undefined; return { version: 1, mode: value?.mode === "visual" || value?.mode === "code" ? value.mode : "code", visual: value?.visual?.root ? value.visual as VisualWidgetDocument : createDefaultVisualDocument(), source: { html: value?.source?.html ?? "<main><h2>Custom widget</h2></main>", css: value?.source?.css ?? "", js: value?.source?.js ?? "" }, permissions: value?.permissions ?? {} }; }
