import { CloudSun, LoaderCircle, MapPin, RefreshCw } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import type { DesktopWidget } from "../../types/widget";

type Weather={temperature:number;apparent:number;code:number;wind:number;location:string;updated:string};
const cacheKey=(id:string)=>`weather-cache-${id}`;
export function WeatherWidget({widget}:{widget:DesktopWidget}) {
 const location=String(widget.data?.location??"New Delhi");const units=widget.data?.units==="fahrenheit"?"fahrenheit":"celsius";const [weather,setWeather]=useState<Weather|null>(()=>{try{return JSON.parse(localStorage.getItem(cacheKey(widget.id))??"null")}catch{return null}});const [loading,setLoading]=useState(false);const [error,setError]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const geo=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(location)}&count=1&language=en&format=json`).then(r=>r.json());const place=geo.results?.[0];if(!place)throw new Error("Location not found");const data=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${place.latitude}&longitude=${place.longitude}&current=temperature_2m,apparent_temperature,weather_code,wind_speed_10m&temperature_unit=${units}`).then(r=>r.json());const next={temperature:data.current.temperature_2m,apparent:data.current.apparent_temperature,code:data.current.weather_code,wind:data.current.wind_speed_10m,location:`${place.name}${place.country_code?`, ${place.country_code}`:""}`,updated:new Date().toISOString()};setWeather(next);localStorage.setItem(cacheKey(widget.id),JSON.stringify(next))}catch(e){setError(e instanceof Error?e.message:"Weather unavailable")}finally{setLoading(false)}},[location,units,widget.id]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),Math.max(5,widget.settings.refreshInterval)*60_000);return()=>clearInterval(timer)},[load,widget.settings.refreshInterval]);
 return <div className="flex h-full flex-col justify-between"><div className="flex items-start gap-3"><CloudSun className="text-accent" size={42}/><div><div className="text-3xl font-semibold">{weather?`${Math.round(weather.temperature)}°${units==="fahrenheit"?"F":"C"}`:"Weather"}</div><div className="flex items-center gap-1 text-xs text-muted"><MapPin size={11}/>{weather?.location??location}</div></div><button title="Refresh weather" onClick={()=>void load()} className="ml-auto rounded-md p-2 hover:bg-black/10">{loading?<LoaderCircle className="animate-spin" size={15}/>:<RefreshCw size={15}/>}</button></div>{weather&&<div className="grid grid-cols-2 gap-2 text-sm"><span>Feels like {Math.round(weather.apparent)}°</span><span>Wind {Math.round(weather.wind)} km/h</span></div>}<div className="text-xs text-muted">{error ? error : weather ? `Updated ${new Date(weather.updated).toLocaleTimeString()}` : "Loading Open-Meteo…"}</div></div>
}
